### ISSUE TITLE
Support Kotlin nullable information in Spring MVC parameters

### ISSUE THREAD

**Issue by rocketraman** [sdeleuze/spring-kotlin#1]
Spring MVC now supports defining fields with the JDK8 `Optional` type to indicate that the parameter is optional (cool!).

Kotlin has fields which can be marked as a nullable type e.g. `String?` vs `String`. This information should be used by Spring MVC in the same way as `Optional`.

See: https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.reflect/-k-type/

This issue copied over from https://jira.spring.io/browse/SPR-14165 at the suggestion of @sdeleuze .

**Comment by sdeleuze** [comment]
Closing this issue as we are going to try to integrate that feature directly in Spring Framework if possible, as explained [here](https://jira.spring.io/browse/SPR-14165?focusedCommentId=128819&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-128819).
